Repository AET-DevOps25/team-LECture-bot, pull requests merged in 2025-06, with the labels that each got.

#14 Added component diagrams architecture
  docs/architecture.drawio
  docs/component-diagram-explanation.md
  docs/component-diagram-plantuml-version.png
  docs/component-diagram.png
Labels: documentation

#44 31 create deployment infra
  .github/workflows/build_docker.yml
  .github/workflows/deploy_docker.yml
  .gitignore
  client/src/config.ts
  client/src/main.tsx
  client/src/pages/SignUpPage.tsx
  compose.aws.yml
  helm/README.md
  helm/lecture-bot-app/Chart.yaml
  helm/lecture-bot-app/templates/app-config.yaml
  helm/lecture-bot-app/templates/client-config.yaml
  helm/lecture-bot-app/templates/client-deployment.yaml
  helm/lecture-bot-app/templates/client-service.yaml
  helm/lecture-bot-app/templates/db-deployment.yaml
  helm/lecture-bot-app/templates/db-init-configmap.yaml
  helm/lecture-bot-app/templates/db-service.yaml
  helm/lecture-bot-app/templates/ingress.yaml
  helm/lecture-bot-app/templates/pvc.yaml
  helm/lecture-bot-app/templates/server-deployment.yaml
  helm/lecture-bot-app/templates/server-service.yaml
  helm/lecture-bot-app/values.yaml
  infra/README.md
  infra/ansible/playbook.yml
  infra/ansible/roles/docker/tasks/install_packages.yml
  infra/ansible/roles/docker/tasks/main.yml
  infra/ansible/roles/docker/tasks/post_install.yml
  infra/terraform/.terraform.lock.hcl
  infra/terraform/main.tf
  infra/terraform/terraform.tfvars
  server/src/main/java/com/lecturebot/config/SecurityConfig.java
Labels: CI/CD

#55 Login e2e done (Client + Server)
  .DS_Store
  .github/workflows/deploy_docker.yml
  .gitignore
  client/.dockerignore
  client/Dockerfile
  client/package-lock.json
  client/package.json
  client/public/config.json
  client/src/App.tsx
  client/src/api/apiClient.ts
  client/src/components/auth/ProtectedRoute.tsx
  client/src/context/AuthContext.tsx
  client/src/main.tsx
  client/src/pages/SignInPage.tsx
  client/src/router/index.tsx
  client/src/utils/storage.ts
  compose.aws.yml
  docker-compose.yml
  helm/lecture-bot-app/values.yaml
  server/.classpath
  server/.factorypath
  server/.project
  server/.settings/org.eclipse.buildship.core.prefs
  server/.settings/org.eclipse.jdt.apt.core.prefs
  server/.settings/org.eclipse.jdt.core.prefs
  server/README.md
  server/build.gradle
  server/src/main/java/com/lecturebot/config/SecurityConfig.java
  server/src/main/java/com/lecturebot/controller/AuthController.java
  server/src/main/java/com/lecturebot/dto/LoginResponse.java
  server/src/main/java/com/lecturebot/security/JwtAuthenticationFilter.java
  server/src/main/java/com/lecturebot/security/JwtTokenProvider.java
  server/src/main/java/com/lecturebot/service/UserService.java
  server/src/main/resources/application.properties
Labels: documentation, enhancement, server, frontend
